image: docker:24.0

services:
  - name: docker:24.0-dind
    command: ["--tls=false"]

stages:
  - build

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""
  DOCKER_DRIVER: overlay2

build_trezor_one:
  stage: build
  privileged: true
  before_script:
    - apk add --no-cache bash git wget curl ca-certificates
  script:
    - chmod +x build-docker.sh
    - ./build-docker.sh --repository . --models T1B1 HEAD
  artifacts:
    paths:
      - build/
    expire_in: 7 days
